services:
    vasek_purchart.console_errors.console.console_exception_listener:
        class: 'VasekPurchart\ConsoleErrorsBundle\Console\ConsoleExceptionListener'
        arguments:
            - '@vasek_purchart.console_errors.console.logger'
            - '%vasek_purchart.console_errors.exception.log_level%'
        tags:
            -
                name: 'kernel.event_listener'
                event: 'console.error'
                priority: '%vasek_purchart.console_errors.exception.listener_priority%'
